---
Name: govtnz-guidance
---
GovtNZ\Guidance\GuidancePage:
  extensions:
    - GovtNZ\Guidance\DescriptionExtension
GovtNZ\Guidance\HubPage:
  extensions:
    - GovtNZ\Guidance\DescriptionExtension
SilverStripe\ORM\DatabaseAdmin:
  classname_value_remapping:
    GuidancePage: 'GovtNZ\Guidance\GuidancePage'
    HubPage: 'GovtNZ\Guidance\HubPage'
